### ISSUE TITLE
The link of image files of Cambridge landmarks  is invalid

### ISSUE THREAD

**Issue by zhuixunforever** [Tangshitao/Dense-Scene-Matching#4]
Hi, thanks for your interesting work.

But the link of image files of Cambridge landmarks seems to be invalid, can you share with me the image files you download?

**Comment by Tangshitao** [comment]
I use the public available images of Cambridge landmarks. The link here is the official link of the dataset, and it seems the sever is down.

**Comment by zhuixunforever** [comment]
Yes, and I sent an email to the author several days ago but got no response.  Can you share with me the dataset you downloaded?

**Comment by Tangshitao** [comment]
I don't have enough space in Google Drive to share this dataset.

**Comment by zhuixunforever** [comment]
I would appreciate you if you could provide the Great Court and Street of Cambridge.

**Comment by zhuixunforever** [comment]
Hi, this is the new official download link of Cambridge. https://github.com/GrumpyZhou/visloc-apr/issues/3#issuecomment-869863467
